spring:
  application:
    name: "LeaderBoard"

  profiles:
    active: in-memory

  datasource:
    url: jdbc:h2:file:./data/leaderboarddb  # In-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password: Brijesh@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Options: create, update, validate, none
    show-sql: true  # Enables SQL query logging
  h2:
    console:
      enabled: true  # Enables H2 web console
      path: /h2-console  # Access URL: http://localhost:8080/h2-console
      settings:
        trace: false
        web-allow-others: false  # Set to true if you need remote access