version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Brijesh@123
      MYSQL_DATABASE: leaderboard
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Brijesh@123
    ports:
      - "3306:3306"
    volumes:
      - /Users/ibrijesh/Desktop/mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: Run an initialization script

volumes:
  mysql_data:
    driver: local
